<a href="https://colab.research.google.com/github/BarbaraLipinska24/data-science-bootcamp/blob/main/01_wprowadzenie/02_Algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Norma wektora

In [3]:
import numpy as np
v1=np.array([1,4])
v1

np.linalg.norm(v1)

4.123105625617661

2.Norma euklidesowa

In [5]:
v2=np.array([-10,10,13])
np.linalg.norm(v2)

19.209372712298546

3. Odległość dwóch punktów na płaszczyźnie


In [8]:
p=np.array([3,0])
q=np.array([0,4])

np.linalg.norm(p-q)

5.0

4.Odległość dwóch punktów w przestrzeni R^n

In [10]:
p=np.array([3,0,1])
q=np.array([1,0,4])

np.linalg.norm(p-q)

3.605551275463989

5.Mnożenie macierzy

In [16]:
X=np.array([[1,5],[6,7]])
Y=np.array([[1],[3]])

Z=np.dot(X,Y)
print(Z)

[[16]
 [27]]


6. Wyznacznik macierzy

In [33]:
A=np.arange(1,26)
A=A.reshape(5,-1)
print(A)
np.linalg.det(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


0.0

7.Ślad macierzy


In [35]:
np.trace(A)

65

8.MAcierz jednostkowa

In [36]:
np.eye(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

9.Macierz odwrotna

In [43]:
A=np.array([[2,4],[-1,3]])
B=np.linalg.inv(A)

print(A)
print(B)

np.set_printoptions(precision=4,suppress=True)
C=np.dot(A,B)

print(C)

[[ 2  4]
 [-1  3]]
[[ 0.3 -0.4]
 [ 0.1  0.2]]
[[1. 0.]
 [0. 1.]]


10. Macierz transponowana

In [45]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [46]:
A.T

array([[ 2, -1],
       [ 4,  3]])

11. Rozwiązywanie układów równań

