<a href="https://colab.research.google.com/github/BarbaraLipinska24/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2. Typy danych

In [3]:
import numpy as np

A=np.array([1,2,3])
A.dtype

dtype('int64')

In [4]:
A=np.array([3.0,2.0,4.0])
A.dtype

dtype('float64')

In [8]:
A=np.array([1.0,2.0,3.0],dtype='complex')
A.dtype

dtype('complex128')

In [9]:
print(A)

[1.+0.j 2.+0.j 3.+0.j]


In [10]:
A=np.array([True,False])
A.dtype

dtype('bool')

In [12]:
A=np.array([24,120,230],dtype=np.int8)
A.dtype
A

array([ 24, 120, -26], dtype=int8)

3. Tworzenie tablic

In [14]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
np.zeros(shape=(4,10),dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [17]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.ones(shape=(5,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
np.full(shape=(3,3),fill_value=4,dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(start=5,stop=10)

array([5, 6, 7, 8, 9])

In [24]:
np.arange(start=10,stop=100,step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [25]:
np.arange(start=100,stop=10,step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [27]:
np.arange(start=0,stop=1,step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [30]:
np.linspace(start=0,stop=1,num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [33]:
A=np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
A.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
A.reshape(3,-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

4. Podstawowe operacje na tablicach


In [40]:
A=np.array([3,1,4,2])
B=np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [41]:
A+B

array([6, 0, 7, 4])

In [42]:
A-B

array([0, 2, 1, 0])

In [43]:
A*B

array([ 9, -1, 12,  4])

In [45]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [50]:
np.add(A,B)

array([6, 0, 7, 4])

In [51]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [52]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [53]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [46]:
A+3

array([6, 4, 7, 5])

In [47]:
A-3

array([ 0, -2,  1, -1])

In [48]:
2*A

array([6, 2, 8, 4])

In [49]:
A+3*B

array([12, -2, 13,  8])

In [56]:
X=np.array([[1,3],[-2,0]])
Y=np.array([[6,0],[-1,2]])
print(X,'\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [58]:
X*Y

array([[6, 0],
       [2, 0]])

In [59]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [60]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [61]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [62]:
X@Y

array([[  3,   6],
       [-12,   0]])